image: $REGISTRY_CI/gitlab-ci-base:buster

variables:
  DOCKER_HOST: tcp://localhost:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  GIT_DEPTH: 10

stages:
  - build
  - sync

build&test:
  stage: build
  script:
    - docker-compose up -d --build
    - sleep 200
    - docker-compose logs
    - curl http://127.0.0.1:8096
  tags:
    - gcp-default-runner-prod

sync:
  stage: sync
  script:
    - git clone --mirror https://$GITLAB_USER:$GITLAB_PASSWORD@gitlab.hipay.org/pi-ecommerce/hipay-docker-magento2.git
    - cd hipay-docker-magento2.git
    - git push --mirror https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/hipay/hipay-docker-magento2.git
  allow_failure: true
  tags:
    - gcp-default-runner-prod
