version: '3'

services:
  magento2:
    container_name: magento2-$CI_JOB_ID
    image: hipay/hipay-magento2
    environment:
      MAGE_DB_HOST: mysql
      MAGE_DB_PORT: 3306
      GITHUB_API_TOKEN: $GITHUB_API_TOKEN
      MAGE_ACCOUNT_PRIVATE_KEY: $MAGE_ACCOUNT_PRIVATE_KEY
      MAGE_ACCOUNT_PUBLIC_KEY: $MAGE_ACCOUNT_PUBLIC_KEY
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - centralization
      - outside

  db:
    container_name: mysql-$CI_JOB_ID
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=magento2
    networks:
      - centralization
      - outside


networks:
  centralization:
    internal: true
  outside:
    external: true

