web:
  container_name: magento2
  build: .
  ports:
    - "80:80"
  links:
    - db
db:
  container_name: mysql
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
  ports:
    - "3307:3306"
