web:
  container_name: magento2
  build: .
  ports:
    - "8080:80"
  links:
    - db
  env_file:
    - env/mage.env.sample
    - env/module.env.sample
db:
  container_name: mysql
  image: mysql:5.6
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
  ports:
    - "3307:3306"
